spring:
  application:
    name: zuul
    
server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    service:
      path: /service/**
      service-id: service
    customer:
      path: /customer/**
      service-id: customer