spring:
  application:
    name: zull
    
server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
      
zuul:
  routes:
    fund:
      path: /service/**
      service-id: service