spring:
  application:
    name: eureka
    
server:
  port: 8761
  
eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/