spring:
  application:
    name: admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile
          
server:
  port: 9999
  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
